language: node_js

node_js:
  - 0.11
  - 0.10

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y quota quotatool supervisor
  - sudo apt-get install -y python-pip python-m2crypto
  - sudo pip install shadowsocks
  - sudo mkdir /etc/shadowsocks

script: npm run test-all-config

services:
  - mongodb
  - redis-server
